.dockerignore, .doppler-ci, .gitattributes, .gitlint, Dockerfile, Jenkinsfile, build-n-publish.sh, cdn-helpers/prepare.sh, cdn-helpers/upload.sh, gitlint.sh, package.json, verify-w-docker.sh
=> chore add ci

Dockerfile, Jenkinsfile, package-lock.json, package.json, webpack.config.js, webpack2.config.js
Add continuous deployment
For this step, it added a second webpack build with the assets manifest file.
TODO:
-  Improve this config with just one build
- Add publicPath dynamically at WebpackManifestPlugin
- Remove unnecessary build files 
- Set webpack mode dynamically
=> Continuous deployment

webpack.config.js, webpack2.config.js
=> ci: set fonts path

src/controllers/automation/automationCompleteInformationCtrl.js, src/controllers/automation/automationTaskReportsCtrl.js, src/controllers/lists/formIntegrateCtrl.js, src/css/app/libs/iconfont/_icon-font.scss, src/css/app/templates/automation/_editor-canvas.scss, src/directives/automation/editor/dpEditorListsScheduledGrid.js, src/directives/dp-templates.js, src/partials/automation/CompleteInformation.html, src/partials/automation/ReportDetailsView.html, src/partials/automation/editor/directives/dp-editor-lists-scheduled-grid.html, src/partials/automation/editor/directives/panel/dp-editor-panel-sms.html, src/partials/templates/dp-templates.html, src/services/automation/editor/automation.js, src/services/automation/editor/automationDataservice.js, src/services/automation/editor/components/initialConditions/CampaignBehaviorCondition.js, src/services/automation/editor/components/initialConditions/ScheduledDateCondition.js, src/services/automation/editor/warningsStepsService.js, src/services/automation/reportsService.js, src/services/templates/templatesService.js
=> Update project from angularJs

webpack.config.js, webpack2.config.js
Add rule to save image at /static/images
Related to: [DOP-1315](https://makingsense.atlassian.net/browse/DOP-1315)
[DOP-1315]: https://makingsense.atlassian.net/browse/DOP-1315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOP-1315  - Set image path at webpack

webpack.config.js, webpack2.config.js
remove svg files on font rule at webpack
=> DOP-1315 - webpack remove svg from fonts

src/automationEditorModule.js, src/controllers/automation/automationGridCtrl.js, src/directives/automation/editor/dpEditorTypes.js, src/partials/automation/editor/directives/dp-editor-types.html, src/partials/automation/editor/index.html, src/partials/automation/taskGrid.html, src/services/automation/editor/automation.js
Change automation select type logic from editor module to the grid module
Fixes: [DOP-1322](https://makingsense.atlassian.net/browse/DOP-1322)
to
https://user-images.githubusercontent.com/83654756/231796548-becc405a-96ed-4688-9a5a-1f25db77d3c0.mp4
[DOP-1316]: https://makingsense.atlassian.net/browse/DOP-1316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOP-1322]: https://makingsense.atlassian.net/browse/DOP-1322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOP-1322 - Change automation type url page

src/partials/automation/editor/directives/dp-editor-template-preview.html
Add bottom padding  for scroll at automation template preview page
=> DOP-1648 - fix visual issue 

webpack2.config.js
Group lib.js app.js directive.js on on js file
=> DOP-1375 - Group all js file on app.js

src/directives/automation/editor/dpEditorTemplate.js
original cards position
sorted
=> DOP-1379 - Sort automation template cards

package-lock.json, package.json, src/automationEditorModule.js, webpack2.config.js
remove the redirection to automationMFE
Fixes: [DOP-1374](https://makingsense.atlassian.net/browse/DOP-1374) 
[DOP-1374]: https://makingsense.atlassian.net/browse/DOP-1374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOP-1374 - Remove replace redirection mfe

src/services/automation/editor/automation.js
Fixes: [DOP-1387](https://makingsense.atlassian.net/browse/DOP-1387)
Related to https://github.com/MakingSense/Doppler/pull/10131
[DOP-1387]: https://makingsense.atlassian.net/browse/DOP-1387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix hasBlockedList when suscriptionLists is not defined

src/partials/automation/editor/directives/header/dp-editor-save.html, src/partials/automation/editor/directives/header/dp-editor-undoredo.html, src/partials/automation/editor/directives/panel/dp-editor-panel-step-tip.html, src/partials/automation/editor/lists-grid.html, src/partials/controlPanel/landing-pages-domains/configureCustomDomain.html, src/partials/controlPanel/landing-pages-domains/domainVerificationError.html, src/partials/shared/checkbox.html, src/partials/shared/ellipsis-with-tooltip.html, src/partials/shared/graph.html, src/partials/shared/loader.html, src/partials/shared/loading.html, src/partials/shared/modalProcessFile.html, src/partials/shared/modalYesOrNo.html, src/partials/shared/preview.html, src/partials/templates/empty.html
=> Remove BOM from partial html files

package-lock.json, package.json, src/automationEditorModule.js, webpack2.config.js
This reverts commit 79c14bb8712b9c0ca4a5a4a14997c5bc0a0217d5, reversing changes made to 1a43dba6c687d2ddf5e60e2a9bf97a0094557c2d.
=> Revert "Merge pull request #24 from FromDoppler/DOP-1374-automation-editor-switch"

package-lock.json, package.json, src/automationEditorModule.js, webpack2.config.js
This reverts commit a570b87a66573957a0e54f8138aab4fcaf9f8046.
=>  DOP-1374 - Replace automation editor by the new MFE

src/css/app/templates/_templates.scss, src/i18n/automation-dicc-en.js, src/i18n/automation-dicc-es.js, src/partials/templates/dp-templates.html
fix campaign automation template
=> DOP-1393 - Automation campaing template fix

src/automationEditorModule.js
=> DOP-1393 - declare undefined object

src/directives/dp-on-error-src.js, src/services/shared/pollService.js
=> DOP-1394 - add polling service

src/css/app/templates/_types.scss, src/partials/automation/editor/directives/dp-editor-template.html, src/services/automation/taskService.js
set automation card with new feature mark
=> DOP-1400 Set automation template card as new feature

src/css/app/templates/_types.scss, src/partials/automation/editor/directives/dp-editor-template.html
Fix:
1. set template card as new feature status independently
2. update automation card description left margin
=> DOP-1400 - Set template card as new feature fix

src/partials/templates/dp-templates.html
=> DOP-1413 - Update content template campaign mark

src/css/app/templates/automation/_editor.scss, src/directives/automation/editor/dpEditorListsGrid.js, src/directives/automation/editor/footer/dpEditorFooter.js, src/partials/automation/editor/directives/dp-editor-domains-grid.html, src/partials/automation/editor/directives/dp-editor-import-html.html, src/partials/automation/editor/directives/dp-editor-lists-grid.html, src/partials/automation/editor/directives/footer/dp-editor-footer.html
Fix: visual issue at footer border
=> DOP-1408 - Tooter border issue

src/i18n/automation-dicc-en.js, src/i18n/automation-dicc-es.js, src/partials/automation/editor/directives/dp-editor-template.html
=> DOP-1430 - update automation template content

src/i18n/automation-dicc-en.js, src/i18n/automation-dicc-es.js
Related to https://github.com/MakingSense/Doppler/pull/10201
=> [DOI-1052] Add jumpseller in dropdown for abandoned carts

src/directives/automation/editor/dpEditorListsGrid.js, src/partials/automation/editor/directives/dp-editor-lists-grid.html
Add rules to avoid infinity loops for automation type subscription list
Related: [DOP-1475 ](https://makingsense.atlassian.net/browse/DOP-1475 )
=> DOP-1475 - Avoid infinity loops for subscription list

src/services/automation/taskService.js
It's related to this one: https://github.com/MakingSense/Doppler/pull/10339
=> feat: consider IsNewFeature flag from backend

src/services/templates/templatesService.js
Add campaign param to exit url to force automation save
Context:
Force automation save for update dynamic component 
Issue:
When the user updates the unlayer campaign and after that starts the automation the method HasDynamicContent returns the last change before that update, and then the response is wrong
=> DOP-1397 Update exit url unlayer

src/services/automation/editor/components/WhatsappComponent.js, src/services/automation/editor/components/WhatsappComponent.schema.json
=> DOP-1585 - Whatsapp component

src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js, src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html, src/services/automation/editor/components/WhatsappComponent.js, src/services/automation/editor/whatsappDataservice.js
Fix: Update whatsapp panel
- Add variables setting
- Send whatsApps test
- Add services to request room and template list
=> DOP-1597  - Update whatsApp panel

src/services/automation/editor/componentsDataservice.js
=> DOP-1601 - Sort new step component

src/directives/automation/editor/canvas/dpEditorNewStep.js, src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js, src/directives/automation/editor/panel/initialConditions/dpEditorPanelCampaignBehaviorCondition.js, src/partials/automation/editor/directives/panel/initialConditions/dp-editor-panel-campaign-behavior-condition.html, src/partials/automation/taskGrid.html, src/services/automation/editor/componentsDataservice.js
Fix:
- update warning logic for new step component
- fix template initial setting
- remove confirmation email sending at initial condition for automation distinct to campaign behavior
- temporal remove report link for whatsapp automation  type at automation grid
=> DOP-1585 - some WhatsApp fix and updates

src/directives/automation/editor/panel/dpEditorPanel.js
Fix: hide the report section at the side panel
Panel with report
Panel without report
=> DOP-1597 - Temporal hide panel report section

src/partials/automation/editor/directives/panel/initialConditions/dp-editor-panel-campaign-behavior-condition.html
Fix: show Scheduled Send Out setting
=> DOP-1592 - Initial condition fix

src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js
fix: add params for sendWhatsappTest request method
=> DOP-1597 - Add params for sendWhatsappTest

src/directives/automation/editor/dpEditorTemplate.js
Fix: update automation template order
TODO: TODO: Analyze if  it is a better option to add a second method to set priority to items with a new feature flag active
=> DOP-1616 - Update automation template order

src/services/automation/editor/componentsDataservice.js
Fix: Enable WhatsApp component for each automation
=> DOP-1615 - Enable WhatsApp component for each automation

src/i18n/automation-dicc-en.js, src/i18n/automation-dicc-es.js, src/partials/automation/editor/directives/dp-editor-types.html
Modify content string and key value
=> [DOW-43] replace content for pending and confirmed order

src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js, src/i18n/automation-dicc-en.js, src/i18n/automation-dicc-es.js, src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html
Fix: add template variables to the payload for the WhatsApp request test and UI validation
Ticket: [DOP-1620](https://makingsense.atlassian.net/browse/DOP-1620)
https://github.com/user-attachments/assets/0b733297-4820-417b-85a4-aac6c863e5bb
[DOP-1620]: https://makingsense.atlassian.net/browse/DOP-1620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOP-1620 - Update request to send WhatsApp test

src/css/doppler-common/modules/_forms.scss, src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js, src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html, src/services/automation/editor/components/WhatsappComponent.js
fix: add template preview by beplic API
=> DOP-1619 - Whatsapp template preview

src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js
fix: remove commit: refactor: move update src frame
=> DOP-1679 - fix whatsapp preview

src/directives/automation/editor/canvas/dpEditorNewStep.js, src/directives/automation/editor/dpEditorTemplate.js, src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js, src/i18n/automation-dicc-en.js, src/i18n/automation-dicc-es.js, src/partials/automation/editor/directives/dp-editor-template.html, src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html, src/services/automation/editor/whatsappDataservice.js
Fix:
- Set conversations link by environment
- improve error message for beplic request
TODO: define the URL for not WhatsApp credit, It now is conversation link
=> DOP-1583 - WhatsApp link fix

src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js, src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html
Fix: 
- update variables dropdown label (translate)
- update placeholder whatsapp phone test
=> DOP-1583 - Improve whatsapp panel

src/directives/automation/editor/dpEditorTemplate.js
Refactor: remove unused sort logic
=> DOP-1628 - remove sort logic

src/directives/automation/editor/canvas/dpEditorNewStep.js, src/directives/automation/editor/dpEditorTemplate.js, src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js, src/partials/automation/editor/directives/dp-editor-template.html, src/services/automation/editor/whatsappDataservice.js
Fix: update conversations plan link by plan type
=> DOP-1643 - Update conversations plan link

src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js, src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html
Fix: set template property at wsp model
=> DOP-1649  - Add multimedia template for wsp

src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js, src/i18n/automation-dicc-en.js, src/i18n/automation-dicc-es.js, src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html, src/services/automation/editor/whatsappDataservice.js
Fix: Add upload button 
Update PR refer to [DOP-1650](https://github.com/MakingSense/Doppler/pull/10715)
https://github.com/user-attachments/assets/944357f9-0158-40df-bfe4-071a26001e87
error screen
[DOP-1650]: https://makingsense.atlassian.net/browse/DOP-1650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOP-1649 - update multimedia link

src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js
fix: update object response with new endpoint
=> DOP-1649 - Whatsapp update response object

src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js, src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html
Fix: Add some fix and improves
=> DOP-1649 multimedia template wsp file upload fixs

src/i18n/automation-dicc-en.js, src/i18n/automation-dicc-es.js, src/partials/automation/editor/directives/panel/dp-editor-panel-whatsapp.html
fix:
set url help link
remove space between send a test message and link
=> Update whatsapp help link

src/directives/dp-templates.js, src/services/automation/editor/components/AutomationComponent.js
fix: set template category base of automationTemplateType
=> DOP-1677 adapt template category

src/directives/automation/editor/panel/dpEditorPanel.js, src/directives/automation/editor/panel/initialConditions/dpEditorPanelCampaignBehaviorCondition.js, src/partials/automation/taskGrid.html
Fix: revert commit for see again report link
[DOP-1658](https://makingsense.atlassian.net/browse/DOP-1658)
[DOP-1658]: https://makingsense.atlassian.net/browse/DOP-1658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOP-1658 - Whatsapp report enabled

src/directives/automation/editor/panel/dpEditorPanelWhatsapp.js
fix: set template list empty on new WhatsApp room select
=> improve whatsapp component

package.json, src/css/doppler-common/modules/_modals.scss, src/i18n/automation-dicc-en.js, src/i18n/automation-dicc-es.js, src/partials/automation/automationStartUnexpectedError.html, src/services/automation/editor/automation.js
Identify and treat unexpected errors while starting an automation.
Now, when an unexpected error happens, a modal will be displayed:
Also, fix the error code for FieldUpdateFails. [It's **37** in the Doppler app](https://github.com/MakingSense/Doppler/blob/develop/Doppler.Transversal/Classes/ApplicationErrorCode.cs#L53).
**Updated contents:**
=> Dop 1697 fix errors treatment initializing automation

src/i18n/automation-dicc-en.js, src/i18n/automation-dicc-es.js
Replace blocked list help links
Fixes: https://makingsense.atlassian.net/browse/DOP-1828
=> fix: update links

src/i18n/automation-dicc-en.js, src/i18n/automation-dicc-es.js
Fix: replace link to help for revert a black list
Ticket: [DOP-1852](https://makingsense.atlassian.net/browse/DOP-1834)
[DOP-1852]: https://makingsense.atlassian.net/browse/DOP-1852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOP-1852 - update link for revert black list

src/i18n/automation-dicc-en.js, src/i18n/automation-dicc-es.js
fix: update footer message for incomplete flow
=> DOP-1866 - update content for amost done

src/partials/automation/editor/directives/dp-editor-domains-grid.html
Fix: remove unused logic to show active count subscriber column
=> DOP1870 - Remove if logic to show column
